"""path and step table

Revision ID: 8d8fa8c71a71
Revises: 89608c166ce0
Create Date: 2020-03-07 20:38:26.640656

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8d8fa8c71a71'
down_revision = '89608c166ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_path_description'), 'path', ['description'], unique=False)
    op.create_index(op.f('ix_path_name'), 'path', ['name'], unique=False)
    op.create_index(op.f('ix_path_timestamp'), 'path', ['timestamp'], unique=False)
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['path'], ['path.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step')
    op.drop_index(op.f('ix_path_timestamp'), table_name='path')
    op.drop_index(op.f('ix_path_name'), table_name='path')
    op.drop_index(op.f('ix_path_description'), table_name='path')
    op.drop_table('path')
    # ### end Alembic commands ###
