"""added index to step order

Revision ID: f1e7bc0ab42b
Revises: 5db876e85c5b
Create Date: 2020-03-16 17:05:20.163818

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f1e7bc0ab42b'
down_revision = '5db876e85c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_step_step_order'), 'step', ['step_order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_step_step_order'), table_name='step')
    # ### end Alembic commands ###
