"""fixed backref error on step table

Revision ID: fcb578fd70be
Revises: 8d8fa8c71a71
Create Date: 2020-03-07 20:46:45.790241

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fcb578fd70be'
down_revision = '8d8fa8c71a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('path_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.create_foreign_key(None, 'step', 'path', ['path_id'], ['id'])
    op.drop_column('step', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('path', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.create_foreign_key(None, 'step', 'path', ['path'], ['id'])
    op.drop_column('step', 'path_id')
    # ### end Alembic commands ###
